name: Latex Check before Merge

on: 
  pull_request:
    branches:
      - main
    paths:
      - 'Relazione/**'
      - 'Relazione'

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
    - name: Preparo i file del PR
      uses: actions/checkout@v3.5.2
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        fetch-depth: 4
    - name: Inizio la compilazione
      uses: xu-cheng/latex-action@v2
      with:
        root_file: "*.tex"
        glob_root_file: true
        working_directory: "Relazione/"
        args: "-pdf -file-line-error -halt-on-error"
        post_compile: "latexmk -c"
